---
- name: config_lighttpd | configuring lighttpd
  ansible.builtin.template:
    src: etc/lighttpd/lighttpd.conf.j2
    dest: "{{ lighttpd_config_file }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart lighttpd

- name: config_lighttpd | configuring lighttpd modules
  ansible.builtin.template:
    src: "{{ item + '.j2' }}"
    dest: "{{ '/' + item }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart lighttpd
  with_items:
    - etc/lighttpd/modules.conf
    - etc/lighttpd/conf.d/fastcgi.conf
  when: >
    ansible_os_family == "RedHat"
