---
# tasks file for ansible-lighttpd
- include_tasks: set_facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config_lighttpd.yml
  when: config_lighttpd

- include_tasks: config_php.yml
  when: lighttpd_enable_php
