---
- name: redhat | enabling EPEL repo
  ansible.builtin.yum:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | installing lighttpd
  ansible.builtin.yum:
    name: lighttpd
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | installing lighttpd
  ansible.builtin.dnf:
    name: lighttpd
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | ensuring lighttpd is enabled and started
  ansible.builtin.service:
    name: lighttpd
    state: started
    enabled: true
  become: true
